#!/bin/bash
#
#  Copyright (c) 2016 CheeryLee
#
#  Author: Alexander Pluzhnikov <cheerylee90@gmail.com>
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License as
#  published by the Free Software Foundation; either version 2 of the
#  License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
#  USA
#

set -e 

pwd=$(pwd)
YELLOW='\033[1;33m'
RED='\033[1;31m'
NO_COLOR='\033[0m'
FOLDERS="/bin /sbin /usr/bin"

function usage()
{
	echo -e "The script introduces support for Linux older than 3.4.
	\rIt shows the programs that are not supported by old kernels.\n
	\rusage: check_program_version <path to unpacked tarball>\n
	\rCheck new version at github.com/CheeryLee/ubuntu_touch_scripts\n"
	
	exit 0
}

if [[ -z $1 ]]; then
	usage
fi

TARPATH=$(realpath $1)

for i in $FOLDERS; do
	
	cd $TARPATH$i
	echo -e "${YELLOW}\n==================  $i FOLDER  ==================${NO_COLOR}"
	
	FILENAME=$(find -executable -name \*)
	for i in $FILENAME; do
		if file $i | grep -q "ELF"; then
			VER=$(file $i | cut -d "," -f6 | sed -r 's/ for GNU\/Linux //')
			if [ "$VER" != "2.6.32" ] && [ "$VER" != "2.6.31" ]; then
				i=$(echo $i | cut -d "/" -f2)
				echo -e "${RED}$i is not valid (for $VER)${NO_COLOR}"
				c=$(($c+1))
			fi
		fi
	done
	
	if [[ c -eq 0 ]]; then
		echo "All done! There is no incorrect executables!"
	fi
done
